import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { createCourse, createDepartment, deleteCourse, deleteDepartment, deleteDocument, downloadDocument, getAdmissions, getCourses, getDepartments, getDocuments, getPayments, getStudents, updateAdmissionStatus } from "../services/api";
import ConfirmationModal from "../components/ConfirmationModal";

const columns = { students: [["Student ID", "studentId"], ["Name", "name"], ["Email", "email"], ["Phone", "phone"]], payments: [["Payment ID", "paymentId"], ["Student ID", "studentId"], ["Student", "studentName"], ["Amount", "amount"], ["Status", "status"], ["Mode", "paymentMode"]] };
function AdminPortal() {
    const navigate = useNavigate(); const [tab, setTab] = useState("admissions"); const [data, setData] = useState({ admissions: [], students: [], courses: [], departments: [], payments: [], documents: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [remarks, setRemarks] = useState({}); const [pendingDelete, setPendingDelete] = useState(null); const [departmentForm, setDepartmentForm] = useState({ departmentName: "", description: "" }); const [courseForm, setCourseForm] = useState({ courseName: "", duration: "", fees: "", departmentId: "" });
    const load = useCallback(async () => { setLoading(true); setError(""); try { const [admissions, students, courses, departments, payments, documents] = await Promise.all([getAdmissions(), getStudents(), getCourses(), getDepartments(), getPayments(), getDocuments()]); setData({ admissions, students, courses, departments, payments, documents }); } catch (e) { setError(e.message || "Unable to load admin data."); } finally { setLoading(false); } }, []);
    useEffect(() => { if (!localStorage.getItem("admin")) navigate("/admin/login", { replace: true }); else load(); }, [load, navigate]);
    const decide = async (id, status) => { try { await updateAdmissionStatus(id, status, remarks[id] || ""); await load(); } catch (e) { setError(e.message); } };
    const addDepartment = async (e) => { e.preventDefault(); try { await createDepartment(departmentForm); setDepartmentForm({ departmentName: "", description: "" }); await load(); } catch (e2) { setError(e2.message); } };
    const addCourse = async (e) => { e.preventDefault(); try { await createCourse({ courseName: courseForm.courseName, duration: courseForm.duration, fees: Number(courseForm.fees), department: { departmentId: Number(courseForm.departmentId) } }); setCourseForm({ courseName: "", duration: "", fees: "", departmentId: "" }); await load(); } catch (e2) { setError(e2.message); } };
    const remove = async () => { if (!pendingDelete) return; const { type, id } = pendingDelete; try { if (type === "course") await deleteCourse(id); else if (type === "department") await deleteDepartment(id); else await deleteDocument(id); setPendingDelete(null); await load(); } catch (e) { setError(e.message || `Unable to delete ${type}. It may be in use.`); } };
    const openDocument = async (fileDocument, download) => { try { const blob = await downloadDocument(fileDocument.documentId); const extension = fileDocument.fileName?.split(".").pop()?.toLowerCase(); const type = extension === "pdf" ? "application/pdf" : extension === "png" ? "image/png" : ["jpg", "jpeg"].includes(extension) ? "image/jpeg" : blob.type; const url = URL.createObjectURL(new Blob([blob], { type })); if (download) { const link = window.document.createElement("a"); link.href = url; link.download = fileDocument.fileName || "document"; window.document.body.appendChild(link); link.click(); link.remove(); } else window.open(url, "_blank", "noopener"); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (e) { setError(e.message); } };
    const nav = ["admissions", "students", "courses", "departments", "payments", "documents"];
    const matchesSearch = (row, kind) => { const student = kind === "payments" ? row.admission?.student : row.student; const name = kind === "students" ? row.name : student?.name; const id = kind === "students" ? row.studentId : student?.studentId; const term = search.trim().toLowerCase(); return !term || String(id || "").includes(term) || String(name || "").toLowerCase().includes(term); };
    const simpleTable = (kind) => <table><thead><tr>{columns[kind].map(([name]) => <th key={name}>{name}</th>)}</tr></thead><tbody>{data[kind].filter((row) => matchesSearch(row, kind)).map((row) => <tr key={row.studentId || row.paymentId}>{columns[kind].map(([name, key]) => { const student = row.admission?.student; const value = key === "studentId" ? (kind === "students" ? row.studentId : student?.studentId) : key === "studentName" ? student?.name : row[key]; return <td key={key}>{key === "paymentId" ? `#${value}` : value || "—"}</td>; })}</tr>)}</tbody></table>;
    const admissions = <table><thead><tr><th>ID</th><th>Student</th><th>Course</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.admissions.map((a) => <tr key={a.admissionId}><td>#{a.admissionId}</td><td>{a.student?.name}</td><td>{a.course?.courseName}</td><td>{a.applicationDate}</td><td>{a.status}</td><td>{a.status === "PENDING" ? <div className="flex flex-wrap gap-2"><input value={remarks[a.admissionId] || ""} onChange={(e) => setRemarks({ ...remarks, [a.admissionId]: e.target.value })} placeholder="Remarks" className="rounded border px-2 py-1"/><button onClick={() => decide(a.admissionId, "APPROVED")} className="rounded bg-green-600 px-2 py-1 text-white">Approve</button><button onClick={() => decide(a.admissionId, "REJECTED")} className="rounded bg-red-600 px-2 py-1 text-white">Reject</button></div> : a.remarks || "—"}</td></tr>)}</tbody></table>;
    const courses = <><form onSubmit={addCourse} className="mb-5 grid gap-3 rounded-lg bg-slate-50 p-4 md:grid-cols-5"><input required value={courseForm.courseName} onChange={(e) => setCourseForm({ ...courseForm, courseName: e.target.value })} placeholder="Course name" className="rounded border px-3 py-2"/><input required value={courseForm.duration} onChange={(e) => setCourseForm({ ...courseForm, duration: e.target.value })} placeholder="Duration" className="rounded border px-3 py-2"/><input required type="number" value={courseForm.fees} onChange={(e) => setCourseForm({ ...courseForm, fees: e.target.value })} placeholder="Fees" className="rounded border px-3 py-2"/><select required value={courseForm.departmentId} onChange={(e) => setCourseForm({ ...courseForm, departmentId: e.target.value })} className="rounded border px-3 py-2"><option value="">Department</option>{data.departments.map((d) => <option key={d.departmentId} value={d.departmentId}>{d.departmentName}</option>)}</select><button className="rounded bg-slate-900 px-3 py-2 text-white">Add Course</button></form><table><thead><tr><th>Course</th><th>Department</th><th>Duration</th><th>Fees</th><th></th></tr></thead><tbody>{data.courses.map((c) => <tr key={c.courseId}><td>{c.courseName}</td><td>{c.department?.departmentName}</td><td>{c.duration}</td><td>₹{c.fees}</td><td><button onClick={() => setPendingDelete({ type: "course", id: c.courseId })} className="text-red-600">Delete</button></td></tr>)}</tbody></table></>;
    const departments = <><form onSubmit={addDepartment} className="mb-5 grid gap-3 rounded-lg bg-slate-50 p-4 md:grid-cols-3"><input required value={departmentForm.departmentName} onChange={(e) => setDepartmentForm({ ...departmentForm, departmentName: e.target.value })} placeholder="Department name" className="rounded border px-3 py-2"/><input value={departmentForm.description} onChange={(e) => setDepartmentForm({ ...departmentForm, description: e.target.value })} placeholder="Description" className="rounded border px-3 py-2"/><button className="rounded bg-slate-900 px-3 py-2 text-white">Add Department</button></form><table><thead><tr><th>Department</th><th>Description</th><th></th></tr></thead><tbody>{data.departments.map((d) => <tr key={d.departmentId}><td>{d.departmentName}</td><td>{d.description || "—"}</td><td><button onClick={() => setPendingDelete({ type: "department", id: d.departmentId })} className="text-red-600">Delete</button></td></tr>)}</tbody></table></>;
    const documents = <table><thead><tr><th>Student ID</th><th>Student</th><th>Document Type</th><th>File</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{data.documents.filter((d) => matchesSearch(d, "documents")).map((d) => <tr key={d.documentId}><td>#{d.student?.studentId || "—"}</td><td>{d.student?.name}</td><td>{d.documentType}</td><td>{d.fileName}</td><td>{d.uploadedAt ? new Date(d.uploadedAt).toLocaleDateString() : "—"}</td><td className="space-x-2"><button onClick={() => openDocument(d, false)} className="text-blue-600">View</button><button onClick={() => openDocument(d, true)} className="text-green-600">Download</button><button onClick={() => setPendingDelete({ type: "document", id: d.documentId })} className="text-red-600">Delete</button></td></tr>)}</tbody></table>;
    const content = { admissions, students: simpleTable("students"), courses, departments, payments: simpleTable("payments"), documents }[tab];
    const searchable = ["students", "payments", "documents"].includes(tab);
    return <><ConfirmationModal open={Boolean(pendingDelete)} title={`Delete ${pendingDelete?.type || "item"}?`} message="This action cannot be undone." confirmLabel="Delete" onCancel={() => setPendingDelete(null)} onConfirm={remove}/><div className="min-h-screen bg-slate-100"><header className="flex items-center justify-between bg-slate-900 px-4 py-4 text-white sm:px-6"><div><p className="text-xs text-slate-300">UAMS</p><h1 className="font-semibold">Admin Portal</h1></div><button onClick={() => { localStorage.removeItem("admin"); navigate("/admin/login", { replace: true }); }} className="rounded border border-slate-600 px-3 py-1.5 text-sm">Logout</button></header><div className="p-4 sm:p-6"><div className="mb-6 flex flex-wrap gap-2">{nav.map((item) => <button key={item} onClick={() => { setTab(item); setSearch(""); }} className={`rounded-lg px-3 py-2 text-sm font-medium capitalize ${tab === item ? "bg-slate-900 text-white" : "border bg-white"}`}>{item}</button>)}</div>{error && <div className="mb-4 rounded bg-red-50 p-3 text-red-700">{error}</div>}{loading ? <p className="text-slate-500">Loading...</p> : <section className="overflow-x-auto rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><h2 className="text-lg font-semibold capitalize">{tab}</h2>{searchable && <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by student name or ID" className="rounded-lg border px-3 py-2 text-sm"/>}</div><div className="min-w-max p-5"><style>{`table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;background:#f8fafc;color:#64748b}th,td{padding:12px;border-bottom:1px solid #e2e8f0}`}</style>{content}</div></section>}</div></div></>;
}
export default AdminPortal;
