import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { createAdmission, getCourse, getLoggedInStudent, getStudent, getStudentDocuments } from "../services/api";
import { getDocumentRequirements } from "../utils/documentRequirements";

function Apply() {
    const { courseId } = useParams(); const navigate = useNavigate(); const studentId = getLoggedInStudent()?.studentId;
    const [student, setStudent] = useState(null); const [course, setCourse] = useState(null); const [documents, setDocuments] = useState([]); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
    useEffect(() => { Promise.all([getStudent(studentId), getCourse(courseId), getStudentDocuments(studentId)]).then(([s, c, d]) => { setStudent(s); setCourse(c); setDocuments(d); }).catch((e) => setError(e.message)); }, [studentId, courseId]);
    if (!student || !course) return <div className="p-6 text-slate-500">Loading application form...</div>;
    const required = getDocumentRequirements(course.courseName); const missing = required.filter(([type]) => !documents.some((document) => document.documentType === type));
    const submit = async (event) => { event.preventDefault(); if (missing.length) return setError("Upload all required documents before submitting your application."); if (!confirmed) return setError("Confirm that your information is correct."); setLoading(true); setError(""); try { await createAdmission(studentId, Number(courseId)); navigate("/admission", { replace: true }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
    return <div className="p-4 sm:p-6"><h1 className="text-2xl font-bold">Admission Application</h1>{error && <div className="mt-5 rounded-lg border border-red-200 bg-red-50 p-3 text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 max-w-3xl space-y-6"><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Student Information</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><p><span className="text-slate-500">Name:</span> {student.name}</p><p><span className="text-slate-500">Email:</span> {student.email}</p><p><span className="text-slate-500">Phone:</span> {student.phone}</p><p><span className="text-slate-500">Date of birth:</span> {student.dateOfBirth}</p></div></section><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Selected Course</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><p>{course.courseName}</p><p>{course.department?.departmentName}</p><p>Duration: {course.duration}</p><p>Fee: ₹{course.fees}</p></div></section><section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Mandatory Documents</h2><p className="mt-1 text-sm text-slate-500">Upload these documents before submitting your application.</p></div><Link to={`/documents?courseId=${courseId}`} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Upload Documents</Link></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{required.map(([type, label]) => { const uploaded = !missing.some(([missingType]) => missingType === type); return <div key={type} className={`rounded-lg px-3 py-2 text-sm ${uploaded ? "bg-green-50 text-green-700" : "bg-amber-50 text-amber-700"}`}>{uploaded ? "✓" : "○"} {label} — {uploaded ? "Uploaded" : "Required"}</div>; })}</div></section><label className="flex items-start gap-3 rounded-lg border bg-white p-4"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} className="mt-1"/>I confirm that the above information is correct.</label><button disabled={loading || missing.length > 0} className="rounded-lg bg-slate-900 px-5 py-3 font-medium text-white disabled:cursor-not-allowed disabled:opacity-50">{missing.length ? "Upload Required Documents First" : loading ? "Submitting..." : "Submit Application"}</button></form></div>;
}
export default Apply;
