import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { registerStudent } from "../services/api";

function Register() {
    const navigate = useNavigate();
    const [form, setForm] = useState({ name: "", email: "", password: "", confirmPassword: "", phone: "", dateOfBirth: "", gender: "", address: "" });
    const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
    useEffect(() => { if (localStorage.getItem("student")) navigate("/", { replace: true }); }, [navigate]);
    const change = (e) => setForm({ ...form, [e.target.name]: e.target.value });
    const submit = async (e) => { e.preventDefault(); setError(""); if (form.password !== form.confirmPassword) return setError("Passwords do not match."); if (!/^\d{10,15}$/.test(form.phone)) return setError("Enter a valid phone number."); setLoading(true); try { const { confirmPassword, ...student } = form; await registerStudent(student); navigate("/login", { replace: true, state: { message: "Registration successful. Please sign in and choose a course to apply." } }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
    return <div className="min-h-screen bg-slate-100 p-4 py-10"><div className="mx-auto max-w-2xl rounded-2xl border bg-white p-6 shadow-sm sm:p-8"><h1 className="text-2xl font-bold">Create your student account</h1><p className="mt-1 text-slate-500">You will choose a course and department when you apply for admission.</p>{error && <div className="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">{[["name", "Full Name", "text"], ["email", "Email", "email"], ["password", "Password", "password"], ["confirmPassword", "Confirm Password", "password"], ["phone", "Phone", "tel"], ["dateOfBirth", "Date of Birth", "date"]].map(([name, label, type]) => <label key={name} className="text-sm font-medium">{label}<input required name={name} type={type} value={form[name]} onChange={change} className="mt-1 w-full rounded-lg border px-3 py-2.5" /></label>)}<label className="text-sm font-medium">Gender<select required name="gender" value={form.gender} onChange={change} className="mt-1 w-full rounded-lg border px-3 py-2.5"><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select></label><label className="text-sm font-medium sm:col-span-2">Address<textarea required name="address" value={form.address} onChange={change} className="mt-1 w-full rounded-lg border px-3 py-2.5" /></label><button disabled={loading} className="rounded-lg bg-slate-900 px-4 py-3 font-medium text-white disabled:opacity-50 sm:col-span-2">{loading ? "Creating account..." : "Register"}</button></form><p className="mt-5 text-center text-sm text-slate-600">Already registered? <Link to="/login" className="font-medium text-blue-600">Sign in</Link></p></div></div>;
}
export default Register;
